### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by Phoenix616** [DrOreo002/ChestShopLimiterPremium#1]
Currently there is no license in the repo nor in the source files. I guess one could assume that this is simply GPLv3 as inherited by Bukkit but seeing as there are lots of disagreements regarding the inheritance via API access it would probably be good to properly specify it, especially now that the plugin is discontinued and people might be looked to fork & continue it.

**Comment by DrOreo002** [comment]
Added a MIT license, I don't do plugin development anymore so I guess MIT is the correct one
